In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats


### Question1:
Scenario: A company wants to analyze the sales performance of its products in different regions. They have collected the following data:</br>
   Region A: [10, 15, 12, 8, 14]</br>
   Region B: [18, 20, 16, 22, 25]</br>
   Calculate the mean sales for each region.</br>



In [4]:
region_A = np.array([10, 15, 12, 8, 14])
region_B = np.array([18, 20, 16, 22, 25])
print(f"Mean of Region A is {np.mean(region_A)}")
print(f"Mean of Region B is {np.mean(region_B)}")

Mean of Region A is 11.8
Mean of Region B is 20.2


### Question2: 
Scenario: A survey is conducted to measure customer satisfaction on a scale of 1 to 5. The data collected is as follows:</br>
   [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]</br>
   Calculate the mode of the survey responses.</br>


In [11]:
data = [4, 5, 2, 3, 5, 4, 3, 2, 4, 5]
print(f"Mode of the data is {stats.mode(data)[0]}")


Mode of the data is [4]


### Question3:
Scenario: A company wants to compare the salaries of two departments. The salary data for Department A and Department B are as follows:</br>
   Department A: [5000, 6000, 5500, 7000]</br>
   Department B: [4500, 5500, 5800, 6000, 5200]</br>
   Calculate the median salary for each department.</br>


In [13]:
dept_A = np.array([5000,6000,5500,7000])
dept_B = np.array([4500,5500,5800,6000,5200])
print("Median of departmen A is:", np.median(dept_A))
print("Median of departmen B is:", np.median(dept_B))

Median of departmen A is: 5750.0
Median of departmen B is: 5500.0


### Question4: 
Scenario: A data analyst wants to determine the variability in the daily stock prices of a company. The data collected is as follows:</br>
   [25.5, 24.8, 26.1, 25.3, 24.9]</br>
   Calculate the range of the stock prices.</br>


In [15]:
data = np.array([25.5, 24.8, 26.1, 25.3, 24.9])
print("Range of the data is:", (np.max(data) - np.min(data)))

Range of the data is: 1.3000000000000007


### Question5:
Scenario: A study is conducted to compare the performance of two different teaching methods. The test scores of the students in each group are as follows:</br>
   Group A: [85, 90, 92, 88, 91]</br>
   Group B: [82, 88, 90, 86, 87]</br>
   Perform a t-test to determine if there is a significant difference in the mean scores between the two groups.</br>


Null Hypothesis: Group A and Group B has no differnce in the mean scores.</br>
Alternate Hypothesis: Group A and Group B has significant difference in the mean scores.

In [16]:

group_A = np.array([85, 90, 92, 88, 91])
group_B = np.array([82, 88, 90, 86, 87])


As number of elements in each sample are less than 30 so we have to first check whether both follow normal distribution or not.For checking normal distribution we have to use shapiro test.

In [19]:
from scipy.stats import shapiro

# Perform the Shapiro-Wilk test:
shapiro_groupA = shapiro(group_A)
shapiro_groupB = shapiro(group_B)

print("Shapiro-Wilk test for Group A students:", shapiro_groupA)
print("Shapiro-Wilk test for Group B students:", shapiro_groupB)

Shapiro-Wilk test for Group A students: ShapiroResult(statistic=0.9385504722595215, pvalue=0.6557092666625977)
Shapiro-Wilk test for Group B students: ShapiroResult(statistic=0.9556270837783813, pvalue=0.7772530913352966)


As P-value is  higher than 0.05 we can say that both distributions are having normal distribution.

To check whether both samples have same variance we have to perform levene test.

In [20]:
from scipy.stats import levene

# Perform Levene's test
levene_test = levene(group_A, group_B)
print(levene_test)

LeveneResult(statistic=0.0, pvalue=1.0)


We can see p value is 1 this means it is very high than 0.05 .In the output statistic value is 0,this means both samples have same variance value.</br>
Now we will conduct our t test.

In [21]:
import scipy.stats as stats

t_statistic, p_value = stats.ttest_ind(group_A, group_B)

print("t-statistic:", t_statistic)
print("p-value:", p_value/2)

t-statistic: 1.4312528946642733
p-value: 0.09511985119539167


In [22]:
alpha = 0.05

if p_value < alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Fail to reject the null hypothesis.


### Question6: 
Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:</br>
   Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]</br>
   Sales (in thousands): [25, 30, 28, 20, 26]</br>
   Calculate the correlation coefficient between advertising expenditure and sales.</br>



In [30]:
from scipy.stats import pearsonr
expenditure_data = np.array([10, 15, 12, 8, 14])
sales_data = np.array([25, 30, 28, 20, 26])
pearson_correlation_coeff,_  = pearsonr(expenditure_data, sales_data)
print(pearson_correlation_coeff)

0.8757511375750133


### Question7: 
A survey is conducted to measure the heights of a group of people. The data collected is as follows:</br>
   [160, 170, 165, 155, 175, 180, 170]</br>
   Calculate the standard deviation of the heights</br>


In [31]:
data = np.array([160, 170, 165, 155, 175, 180, 170])
print("standard deviation of given data is: ", np.std(data))

standard deviation of given data is:  7.953949089757174


### Question8: 
A company wants to analyze the relationship between employee tenure and job satisfaction. The data collected is as follows:</br>
   Employee Tenure (in years): [2, 3, 5, 4, 6, 2, 4]</br>
   Job Satisfaction (on a scale of 1 to 10): [7, 8, 6, 9, 5, 7, 6]</br>
   Perform a linear regression analysis to predict job satisfaction based on employee tenure.</br>



In [9]:
input = np.array([2, 3, 5, 4, 6, 2, 4]).reshape(-1,1)
target = np.array([7, 8, 6, 9, 5, 7, 6]).reshape(-1,1)


In [10]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(input,target)

LinearRegression()

In [11]:
lr.coef_

array([[-0.46808511]])

In [12]:
lr.intercept_

array([8.59574468])

### Question9: 
A study is conducted to compare the effectiveness of two different medications. The recovery times of the patients in each group are as follows:</br>
   Medication A: [10, 12, 14, 11, 13]</br>
   Medication B: [15, 17, 16, 14, 18]</br>
   Perform an analysis of variance (ANOVA) to determine if there is a significant difference in the mean recovery times between the two medications.


Null Hypothesis: There is no difference in the mean recovery time between the two medications.</br>
Alternate Hypothesis: There is significant difference in the mean recovery time between the two medications.

In [15]:
data_a = np.array([10, 12, 14, 11, 13])
data_b = np.array([15, 17, 16, 14, 18])

In [16]:
dof_a = len(data_a)
dof_b = len(data_b)

In [18]:
import scipy.stats as stats
f_stat = stats.f_oneway(data_a, data_b)

In [19]:
f_stat

F_onewayResult(statistic=16.0, pvalue=0.003949772803445326)

In [22]:
p_value = f_stat[1]
p_value

0.003949772803445326

In [23]:
alpha = 0.05

if p_value < alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Reject the null hypothesis.


### Question10: 
Scenario: A company wants to analyze customer feedback ratings on a scale of 1 to 10. The data collected is as follows:</br>
[8, 9, 7, 6, 8, 10, 9, 8, 7, 8]</br>
    Calculate the 75th percentile of the feedback ratings.</br>


In [25]:
data = np.array([8, 9, 7, 6, 8, 10, 9, 8, 7, 8])
np.percentile(data, q = 75)

8.75

### Question11: 
Scenario: A quality control department wants to test the weight consistency of a product. The weights of a sample of products are as follows:</br>
    [10.2, 9.8, 10.0, 10.5, 10.3, 10.1]</br>
    Perform a hypothesis test to determine if the mean weight differs significantly from 10 grams.</br>



In this problem as population standard deviation is unknown and sample size is small so we will do t test for verifying the hypothesis.</br>
As we are given the population mean so here we will do single sample t-test.

Null Hypothesis: There is no difference between sample data mean and given population mean.</br>
Alternate hypothesis: There is significant difference between sample data mean and given population mean.

In [28]:
data = np.array([10.2, 9.8, 10.0, 10.5, 10.3, 10.1])
pop_mean = 10


In [27]:
#First we check whether our sample data is normal or not.For this we have to do shapiro test.
from scipy.stats import shapiro

# Perform the Shapiro-Wilk test:
shapiro_data = shapiro(data)

print("Shapiro-Wilk test for Group A students:", shapiro_data)

Shapiro-Wilk test for Group A students: ShapiroResult(statistic=0.9999257922172546, pvalue=0.9999999403953552)


As we can see p value is near 1,so we can say that data is having normal distribution.

In [30]:
import scipy.stats as stats

t_statistic, p_value = stats.ttest_1samp(data, pop_mean)

print("t-statistic:", t_statistic)
print("p-value:", p_value/2)

t-statistic: 1.5126584522688367
p-value: 0.09538797575555051


In [31]:
alpha = 0.05

if p_value < alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Fail to reject the null hypothesis.


### Question12: 
Scenario: A company wants to analyze the click-through rates of two different website designs. The number of clicks for each design is as follows:</br>
    Design A: [100, 120, 110, 90, 95]</br>
    Design B: [80, 85, 90, 95, 100]</br>
    Perform a chi-square test to determine if there is a significant difference in the click-through rates between the two designs.


Null Hypothesis: There is no significant difference in the click through rates between the two designs.</br>
Alternate Hypothesis:  There is significant difference in the click through rates between the two designs.

In [2]:
Design_A = np.array([100, 120, 110, 90, 95])
Design_B = np.array([80, 85, 90, 95, 100])

In [8]:
df = pd.DataFrame({"Design_A": Design_A, "Design_B": Design_B})

In [9]:
from scipy.stats import chi2_contingency
chi2, p_value, dof, expected = chi2_contingency(df)


In [10]:
print("\nChi-Square Statistic: {:.2f}".format(chi2))
print("P-value: {:.4f}".format(p_value))
print("Degrees of Freedom: {}".format(dof))
print("Expected Frequencies: \n{}".format(expected))


Chi-Square Statistic: 6.11
P-value: 0.1910
Degrees of Freedom: 4
Expected Frequencies: 
[[ 96.06217617  83.93782383]
 [109.40414508  95.59585492]
 [106.7357513   93.2642487 ]
 [ 98.73056995  86.26943005]
 [104.06735751  90.93264249]]


In [13]:
# Interpret the results
alpha = 0.05
if p_value < alpha:
    print("\nWe reject the null hypothesis.There is  significant difference in the click through rates between the two designs. ")
else:
    print("\nWe fail to reject the null hypothesis. There is a no significant difference in the click through rates between the two designs.")


We fail to reject the null hypothesis. There is a no significant difference in the click through rates between the two designs.


### Question13: 
Scenario: A survey is conducted to measure customer satisfaction with a product on a scale of 1 to 10. The data collected is as follows:</br>
    [7, 9, 6, 8, 10, 7, 8, 9, 7, 8]</br>
    Calculate the 95% confidence interval for the population mean satisfaction score</br>


As sample has less than 30 values,so we have to use t distribution to calculate the confidence interval.

In [15]:
data = np.array([7, 9, 6, 8, 10, 7, 8, 9, 7, 8])

In [19]:
cnf_interval = stats.t.interval(alpha=0.95, df=len(data)-1, loc=np.mean(data), scale=stats.sem(data)) 
cnf_interval

(7.043561120599888, 8.756438879400113)

### Question14: 
Scenario: A company wants to analyze the effect of temperature on product performance. The data collected is as follows:</br>
    Temperature (in degrees Celsius): [20, 22, 23, 19, 21]</br>
    Performance (on a scale of 1 to 10): [8, 7, 9, 6, 8]</br>
    Perform a simple linear regression to predict performance based on temperature


In [21]:
temp = np.array([20, 22, 23, 19, 21]).reshape(-1,1)
perf = np.array([8, 7, 9, 6, 8]).reshape(-1,1)


In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
temp = StandardScaler().fit_transform(temp)
perf = StandardScaler().fit_transform(perf)

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
model = LinearRegression()

In [29]:
model.fit(temp,perf)

LinearRegression()

In [30]:
print(model.coef_, model.intercept_)

[[0.69337525]] [3.88578059e-16]


### Question15: 
Scenario: A study is conducted to compare the preferences of two groups of participants. The preferences are measured on a Likert scale from 1 to 5. The data collected is as follows:</br>
    Group A: [4, 3, 5, 2, 4]</br>
    Group B: [3, 2, 4, 3, 3]</br>
    Perform a Mann-Whitney U test to determine if there is a significant difference in the median preferences between the two groups.


Null Hypothesis: There is no significant difference in the median preferences between the two groups.</br>
Alternate Hypothesis:There is significant difference in the median preferences between the two groups.

In [31]:
group_A = np.array([4, 3, 5, 2, 4])
group_B = np.array([3, 2, 4, 3, 3])

In [32]:
stat,p_value = stats.mannwhitneyu(group_A, group_B)

In [33]:
p_value

0.380836480306712

In [34]:
alpha = 0.05

if p_value < alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Fail to reject the null hypothesis.


### Question16: 
A company wants to analyze the distribution of customer ages. The data collected is as follows:</br>
    [25, 30, 35, 40, 45, 50, 55, 60, 65, 70]</br>
    Calculate the interquartile range (IQR) of the ages.</br>


In [35]:
data = np.array([25, 30, 35, 40, 45, 50, 55, 60, 65, 70])

In [36]:
iqr = stats.iqr(data)

In [37]:
iqr

22.5

### Question17: 
Scenario: A study is conducted to compare the performance of three different machine learning algorithms. The accuracy scores for each algorithm are as follows:</br>
    Algorithm A: [0.85, 0.80, 0.82, 0.87, 0.83]</br>
    Algorithm B: [0.78, 0.82, 0.84, 0.80, 0.79]</br>
    Algorithm C: [0.90, 0.88, 0.89, 0.86, 0.87]</br>
    Perform a Kruskal-Wallis test to determine if there is a significant difference in the median accuracy scores between the algorithms.


Null Hypothesis: There is no differnce between the median accuracy scores between the algorithms.</br>
Alternate Hypothesis: There is significant difference between median accuracy scores between the algorithms.

In [38]:
 a = np.array([0.85, 0.80, 0.82, 0.87, 0.83])
b = np.array([0.78, 0.82, 0.84, 0.80, 0.79])
c = np.array([0.90, 0.88, 0.89, 0.86, 0.87])

In [40]:
stat,p_value = stats.kruskal(a,b,c)

In [41]:
p_value

0.007840333026249539

In [42]:
alpha = 0.05

if p_value < alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Reject the null hypothesis.


### Question18: 
Scenario: A company wants to analyze the effect of price on sales. The data collected is as follows:</br>
    Price (in dollars): [10, 15, 12, 8, 14]</br>
    Sales: [100, 80, 90, 110, 95]</br>
    Perform a simple linear regression to predict sales based on price.


In [44]:
price = np.array([10, 15, 12, 8, 14]).reshape(-1,1)
sales = np.array([100, 80, 90, 110, 95]).reshape(-1,1)

In [45]:
price = StandardScaler().fit_transform(price)
sales = StandardScaler().fit_transform(sales)

In [46]:
my_model = LinearRegression()

In [47]:
my_model.fit(price,sales)

LinearRegression()

In [48]:
my_model.coef_

array([[-0.89799913]])

In [49]:
my_model.intercept_

array([-2.79154207e-16])

### Question19: 
Scenario: A survey is conducted to measure the satisfaction levels of customers with a new product. The data collected is as follows:</br>
    [7, 8, 9, 6, 8, 7, 9, 7, 8, 7]</br>
    Calculate the standard error of the mean satisfaction score.


In [ ]:
data = np.array([7, 8, 9, 6, 8, 7, 9, 7, 8, 7])

In [50]:
error = stats.sem(data)

In [51]:
error

4.78713553878169

### Question20:
Scenario: A company wants to analyze the relationship between advertising expenditure and sales. The data collected is as follows:</br>
    Advertising Expenditure (in thousands): [10, 15, 12, 8, 14]</br>
    Sales (in thousands): [25, 30, 28, 20, 26]</br>
    Perform a multiple regression analysis to predict sales based on advertising expenditure.


In [52]:
exp = np.array([10, 15, 12, 8, 14]).reshape(-1,1)
sales = np.array([25, 30, 28, 20, 26]).reshape(-1,1)

In [53]:
model1 = LinearRegression()

In [54]:
model1.fit(exp,sales)

LinearRegression()

In [55]:
model1.coef_

array([[1.15243902]])

In [56]:
model1.intercept_

array([12.20121951])